name: HACS Action

on:
  push:
    branches: [main]
    paths:
      - "custom_components/**"
      - "hacs.json"
      - "README.md"
      - ".github/workflows/hacs.yaml"
  pull_request:
    paths:
      - "custom_components/**"
      - "hacs.json"
      - "README.md"
      - ".github/workflows/hacs.yaml"
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    if: github.event_name != 'push' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: HACS Action
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a  # 22.5.0
        with:
          category: "integration"
          ignore: "topics license issues"
